paths:
  raw_data: "data/raw_data"
  processed_data: "data/processed_data"
  templates: "templates"

metadata:
  author: "David Byrne"
  date_created: "2025-08-12"

expt_conditions:
  sae1:
    temp:        150    #degC
    pres:        75     #bar
    CO2:         10     #ppm
    rock_mass:   24.29  #g
    calcite:     0.0    #wt%
    sio2:        0.014080088
    porosity:    43.01  #%
    flow_rate:   5      #ml/hr
    duration:    31     #days
        
  sae2:
    temp:        150    #degC
    pres:        75     #bar
    CO2:         10     #ppm
    rock_mass:   24.29  #g
    calcite:     1.5e-2 #wt%
    sio2:        0.014136678
    porosity:    46.01  #%
    flow_rate:   5      #ml/hr
    duration:    31     #days
    
  sae3:
    temp:        150    #degC
    pres:        75     #bar
    CO2:         2000   #ppm
    rock_mass:   24.30  #g
    calcite:     1.5e-2 #wt%
    sio2:        0.013901478
    porosity:    45.20  #%
    flow_rate:   5      #ml/hr
    duration:    31     #days
    
  sae4:
    temp:        150    #degC
    pres:        75     #bar
    CO2:         600    #ppm
    rock_mass:   24.30  #g
    calcite:     1.5e-2 #wt%
    sio2:        0.013723369
    porosity:    45.20  #%
    flow_rate:   5      #ml/hr
    duration:    31     #days
    
output_flags:
  - name: pH
    type: species
  - name: Total_SiO2(aq)
    type: species
  - name: Total_Ca++
    type: species
  - name: SiO2(am)_VF
    type: mineral
  - name: Calcite_VF
    type: mineral
  - name: Calcite_is_VF
    type: mineral  
